<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CDActivity extends Model
{
    protected $fillable = ['activityType', 'assignDate', 'dueDate', 'estTime'];
    protected $guarded = ['activityID', 'sectionID']; 
    
    /*
     * Table associated with model.
     * 
     * @var string
     */
    
    protected $table = 'Activity';
    
    //We should have used the migrations for our DB again as laravel looks for
    //time stamps autogenerated.
    
    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;
}
