<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StudentActivity extends Model
{
    protected $fillable = ['timeSpent', 'stressLevel', 'comments', 'timeEstimated'];
    protected $guarded = ['userID', 'activityID']; 
    
    /*
     * Table associated with model.
     * 
     * @var string
     */
    
    protected $table = 'StudentActivity';
    
    //We should have used the migrations for our DB again as laravel looks for
    //time stamps autogenerated.
    
    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;
    
    
}
